#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

EXPECTED = {
    "bcftools": "1.24",
    "samtools": "1.24",
    "bwa-mem2": "2.3",
    "gatk4": "4.6.2.0",
    "nextflow": "26.04.6",
    "snakemake-minimal": "7.32.4",
    "pypdfium2": "5.13.0",
    "@modelcontextprotocol/sdk": "1.30.0",
    "zod": "4.4.3",
}
RETIRED = {"poppler", "pdftoppm", "pdftocairo"}

def main() -> int:
    if len(sys.argv) != 4:
        print(
            "usage: validate_stage4_sbom.py SYFT_JSON SPDX_JSON CYCLONEDX_JSON",
            file=sys.stderr,
        )
        return 2

    syft = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    spdx = json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))
    cdx = json.loads(Path(sys.argv[3]).read_text(encoding="utf-8"))
    errors: list[str] = []

    descriptor = syft.get("descriptor") or {}
    if descriptor.get("name") != "syft" or descriptor.get("version") != "1.52.0":
        errors.append("SBOM was not generated by pinned Syft 1.52.0")
    source = syft.get("source") or {}
    if source.get("type") != "image":
        errors.append("SBOM source is not a container image")

    artifacts = syft.get("artifacts")
    if not isinstance(artifacts, list) or len(artifacts) < 250:
        errors.append("final-image SBOM package coverage is unexpectedly small")
        artifacts = artifacts if isinstance(artifacts, list) else []

    by_name: dict[str, set[str]] = {}
    for item in artifacts:
        if not isinstance(item, dict):
            continue
        name = str(item.get("name") or "")
        version = str(item.get("version") or "")
        by_name.setdefault(name, set()).add(version)

    retired = sorted(name for name in by_name if name.casefold() in RETIRED)
    if retired:
        errors.append(
            f"retired PDF runtime components present in final SBOM: {retired}"
        )

    for name, version in EXPECTED.items():
        versions = by_name.get(name, set())
        if version not in versions:
            errors.append(
                f"required runtime component missing from SBOM: {name}=={version}"
            )

    if spdx.get("spdxVersion") != "SPDX-2.3":
        errors.append("SPDX output is not SPDX-2.3")
    if not isinstance(spdx.get("packages"), list) or len(spdx["packages"]) < 250:
        errors.append("SPDX package inventory is unexpectedly small")

    if cdx.get("bomFormat") != "CycloneDX" or cdx.get("specVersion") != "1.7":
        errors.append("CycloneDX output is not version 1.7")
    if not isinstance(cdx.get("components"), list) or len(cdx["components"]) < 250:
        errors.append("CycloneDX component inventory is unexpectedly small")

    if errors:
        for error in errors:
            print(f"FAIL\t{error}")
        return 1

    print(
        f"PASS\tstage4_final_image_sbom\tsyft_artifacts={len(artifacts)} "
        f"spdx_packages={len(spdx['packages'])} "
        f"cdx_components={len(cdx['components'])}"
    )
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
