#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

SYFT_EXPECTED = {
    "pypdfium2": "5.13.0",
    "@modelcontextprotocol/sdk": "1.30.0",
    "zod": "4.4.3",
    "snakemake": "7.32.4",
}
RETIRED = {"poppler", "pdftoppm", "pdftocairo"}


def _load(path: str) -> Any:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _conda_records(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if isinstance(payload, dict):
        packages = payload.get("packages")
        if isinstance(packages, list):
            return [item for item in packages if isinstance(item, dict)]
    return []


def _conda_identity(item: dict[str, Any]) -> tuple[str, str, str]:
    return (
        str(item.get("name") or ""),
        str(item.get("version") or ""),
        str(item.get("build_string") or item.get("build") or ""),
    )


def main() -> int:
    if len(sys.argv) != 6:
        print(
            "usage: validate_stage4_sbom.py "
            "SYFT_JSON SPDX_JSON CYCLONEDX_JSON CONDA_LOCK CONDA_INVENTORY",
            file=sys.stderr,
        )
        return 2

    syft = _load(sys.argv[1])
    spdx = _load(sys.argv[2])
    cdx = _load(sys.argv[3])
    conda_lock = _load(sys.argv[4])
    conda_inventory = _load(sys.argv[5])
    errors: list[str] = []

    if not isinstance(syft, dict):
        errors.append("Syft output is not a JSON object")
        syft = {}
    descriptor = syft.get("descriptor") or {}
    if not isinstance(descriptor, dict):
        descriptor = {}
    if descriptor.get("name") != "syft" or descriptor.get("version") != "1.52.0":
        errors.append("SBOM was not generated by pinned Syft 1.52.0")
    source = syft.get("source") or {}
    if not isinstance(source, dict) or source.get("type") != "image":
        errors.append("SBOM source is not a container image")

    artifacts = syft.get("artifacts")
    if not isinstance(artifacts, list) or len(artifacts) < 1000:
        errors.append("final-image Syft package coverage is unexpectedly small")
        artifacts = artifacts if isinstance(artifacts, list) else []

    typed_artifacts = [item for item in artifacts if isinstance(item, dict)]
    deb_count = sum(1 for item in typed_artifacts if item.get("type") == "deb")
    if deb_count < 90:
        errors.append("final-image Debian/base-image coverage is unexpectedly small")

    by_name: dict[str, set[str]] = {}
    for item in typed_artifacts:
        name = str(item.get("name") or "")
        version = str(item.get("version") or "")
        by_name.setdefault(name, set()).add(version)

    retired = sorted(name for name in by_name if name.casefold() in RETIRED)
    if retired:
        errors.append(
            f"retired PDF runtime components present in final SBOM: {retired}"
        )

    for name, version in SYFT_EXPECTED.items():
        versions = by_name.get(name, set())
        if version not in versions:
            errors.append(
                f"required scanner-visible runtime component missing: {name}=={version}"
            )

    if not isinstance(conda_lock, dict):
        errors.append("Conda lock is not a JSON object")
        conda_lock = {}
    expected_records = _conda_records(conda_lock)
    actual_records = _conda_records(conda_inventory)
    expected = {_conda_identity(item) for item in expected_records}
    actual = {_conda_identity(item) for item in actual_records}
    actual_nonvirtual = {
        identity for identity in actual if identity[0] and not identity[0].startswith("__")
    }
    if len(expected) < 150:
        errors.append("audited Conda lock coverage is unexpectedly small")
    if len(actual_nonvirtual) < 150:
        errors.append("final-image Conda inventory coverage is unexpectedly small")

    missing = sorted(expected - actual_nonvirtual)
    unexpected = sorted(actual_nonvirtual - expected)
    if missing:
        errors.append(
            f"final-image Conda inventory is missing {len(missing)} locked packages"
        )
    if unexpected:
        errors.append(
            f"final-image Conda inventory has {len(unexpected)} unexpected packages"
        )

    retired_conda = sorted(
        identity for identity in actual_nonvirtual if identity[0].casefold() in RETIRED
    )
    if retired_conda:
        errors.append(
            f"retired PDF runtime components present in Conda inventory: {retired_conda}"
        )

    if not isinstance(spdx, dict) or spdx.get("spdxVersion") != "SPDX-2.3":
        errors.append("SPDX output is not SPDX-2.3")
        spdx_packages: list[Any] = []
    else:
        packages = spdx.get("packages")
        spdx_packages = packages if isinstance(packages, list) else []
    if len(spdx_packages) < 1000:
        errors.append("SPDX package inventory is unexpectedly small")

    if (
        not isinstance(cdx, dict)
        or cdx.get("bomFormat") != "CycloneDX"
        or cdx.get("specVersion") != "1.7"
    ):
        errors.append("CycloneDX output is not version 1.7")
        cdx_components: list[Any] = []
    else:
        components = cdx.get("components")
        cdx_components = components if isinstance(components, list) else []
    if len(cdx_components) < 1000:
        errors.append("CycloneDX component inventory is unexpectedly small")

    if errors:
        for error in errors:
            print(f"FAIL\t{error}")
        return 1

    print(
        "PASS\tstage4_final_image_sbom\t"
        f"syft_artifacts={len(typed_artifacts)} "
        f"deb_packages={deb_count} "
        f"conda_packages={len(actual_nonvirtual)} "
        f"spdx_packages={len(spdx_packages)} "
        f"cdx_components={len(cdx_components)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
